# Generated by Django 5.0.6 on 2024-07-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profilephotos/'),
        ),
    ]
